# borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# lint it here: http://lint.travis-ci.org/
language: python
python:
  - 2.7
notifications:
  email: false

# whitelist
branches:
  only:
    - cli

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.0.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.0.0-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis and
  # are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install conda packages
install:
  - conda install --yes -c https://conda.binstar.org/faircloth-lab python=$TRAVIS_PYTHON_VERSION numpy=1.7 biopython=1.62 pytest=2.4.2 abyss velvet lastz mafft

# Run test
script:
  - py.test
